### ISSUE TITLE
Formatting code before commit

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#169]
### Summary

Currently, we have scalafmt formatting as the main code formatter. Also recently it's added as part of the build. Since now 98% of my builds fail on the first attempt I would like to have a git hook so i don't have to deal with this anymore. I feel this would also not be very friendly for the people that would make pull requests since they might not be used to the scalafmt formatter.

**Comment by nicojs** [comment]
A githook sounds user-friendly. However, it is a pain to get it actually _checked into source control_ (since the `.git` is ignored for obvious reasons). So you would need a build step or something to add it.

On top of that: people that might not have installed a JVM will not be able to make a PR. Even not to just fix a typo in the readme (we have been known to have those from time to time 😊). 

As a less invasive sollution, might it be possible to add the formatter to your development environment configuration so that files are automatically formatted if you save a file? That's what we've done recently. We also checkin our vscode configuration. So anyone with the correct plugin installed automatically has formats on save. We've documented this in our [contributing.md](https://github.com/stryker-mutator/stryker/blob/master/CONTRIBUTING.md#code-style) file.

**Comment by hugo-vrijswijk** [comment]
Current idea is to add a sbt task to copy the script over to the user's git folder when the project loads. I think it's safe to assume the user has a JVM if they load sbt. 

> As a less invasive sollution, might it be possible to add the formatter to your development environment configuration so that files are automatically formatted if you save a file? 

Definitely possible. However, this means checking in IDE-specific files. Which I am not a huge fan of. Though it could work fairly well with VS Code. 

Doing this in IntelliJ is slightly more work, I think. IntelliJ's configuration files aren't as user-edit-friendly. On top of that, IntelliJ has it's own default formatter, which is ever so subtly different from Scalafmt (which we use). So we'd also need a way to set it to use the IntelliJ scalafmt formatter. However, the current version of the IntelliJ scalafmt formatter has a hardcoded version of 1.5.1. Support for a more dynamic setting is in the works (in the nightly release), but not properly available yet.
