### ISSUE TITLE
 Full report on the stryker-dashboard

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker4s#284]
See https://github.com/stryker-mutator/stryker-handbook/issues/27

**Comment by hugo-vrijswijk** [comment]
This issue should be fairly straight-forward. We already [support the 'old' stryker dashboard](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/report/DashboardReporter.scala). It shouldn't be much more than just changing the url, api key header and sending the report instead of the payload we send now.

While we're at it, it'd be nice to also add support for GitHub actions.
