### ISSUE TITLE
sbt plugin not found

### ISSUE THREAD

**Issue by greilly** [stryker-mutator/stryker4s#386]
Hi,

The sbt plugin, as identified by the quickstart guide, cannot be found.  SBT is unable to resolve the dependency, and attempting a manual download from https://repo1.maven.org/maven2/io/stryker-mutator/sbt-stryker4s/0.7.2/sbt-stryker4s-0.7.2.jar results in a 404.  It's also not listed from here: https://mvnrepository.com/artifact/io.stryker-mutator.

Thanks,
Greg

**Comment by hugo-vrijswijk** [comment]
Hi, thanks for opening an issue! Where exactly have you added the plugin? It should be under `project/plugins.sbt`, similar to what it is in [Stryker4s itself](https://github.com/stryker-mutator/stryker4s/blob/master/project/plugins.sbt). The maven coordinates are indeed not at the link you provided. Sbt plugins [append the Scala minor and sbt major version to the coordinates](https://repo1.maven.org/maven2/io/stryker-mutator/sbt-stryker4s_2.12_1.0/) and sbt will automatically add those to the build.

Otherwise, is it possible for you to create a small example repository where you are running into the same issue?

**Comment by greilly** [comment]
Thanks, for the project link, Hugo!  I'm still not 100% sure why https://repo1.maven.org/maven2/io/stryker-mutator/sbt-stryker4s/0.7.2/sbt-stryker4s-0.7.2.jar results in a 404, but when I updated my SBT version from 0.13.13 to 1.3.8 (matching the Stryker4s project) SBT was able to pull the 0.7.2 plugin successfully.

I'll take this as a sign that my team should finally update to SBT 1.x, and close this ticket :)

**Comment by hugo-vrijswijk** [comment]
Ah, Stryker4s is not published for sbt 0.13.x, only for 1.x
