### ISSUE TITLE
Ambiguous warning about log-level configuration

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/stryker4s#454]
### Summary

When stryker4s.conf contains the `log-level` key, Stryker4S will log

> WARN  stryker4s.config.ConfigReader$ - The following configuration key(s) are not used, they could stem from an older stryker4s version: log-level.
Please check the documentation at https://github.com/stryker-mutator/stryker4s/blob/master/docs/CONFIGURATION.md for available options.

That same documentation page says log-level is a [valid configuration key](https://github.com/stryker-mutator/stryker4s/blob/master/docs/CONFIGURATION.md#log-level).

### Stryker4s config
```hocon
{
  log-level = debug
}
``` 

### Stryker4s environment

```
stryker4s 0.7.2
```

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |    2.13.1        |
| Build tool & version |    SBT 1.3.10        | 
| Operating System     |  Linux (Debian Buster) and macOS (Catalina) |

**Comment by hugo-vrijswijk** [comment]
`log-level` is a bit of a tricky one. For sbt projects you can set it using a sbt setting (`logLevel in stryker := Level.Debug` in build.sbt or sbt session). The field from the `stryker4s.conf` is not used, so the warning is correct.

In earlier versions of stryker4s `log-level` was configurable from the config file, but it was removed due to it not working well. It was, for me, also the main reason to add the warning about unused fields.

**Comment by mthmulders** [comment]
Thanks!
