### ISSUE TITLE
Cleanup tmp files after mutation run completes or crashes

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/stryker4s#53]
### Summary

Currently when a test run is completed or crashes the tmp folder which was created is not cleaned.
This is not that user-friendly and we should make sure the files which are created as cleaned.

**Comment by legopiraat** [comment]
What we can do is build a try catch around the ProcessMutantRunner and make a finalize block to remove the directory. 

Sadly we copy over all files even the files we don't need, this works fine but there is a but. We are unable to delete the .git folder it seems we don't have access to it. We need a way to exclude some common folders if possible.

**Comment by legopiraat** [comment]
a way to exclude folders:
`path.listRecursively.filterNot(_.name.matches(regex)).foreach(f => f.copyTo(tmpDir / (path.relativize(f).path)))`

And then we can specify some folders we want to ignore because they have no value for us. (the already existing target folder, git folder for example)

**Comment by hugo-vrijswijk** [comment]
Why don't we only copy files listed by git if it's a git repo? I believe that is something Stryker already does

**Comment by legopiraat** [comment]
You are right i was not aware of that. 

Link to the code
https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/core/StrykerOptions.ts

**Comment by hugo-vrijswijk** [comment]
Personally I quite like that solution as it limits how much is unnecessarily copied and should work in 99% of the cases. Perhaps we should just copy the solution. If we implement this we should probably have a config option for that 1% that doesn't use git. Two things I can think of we should maybe pay attention to:

- I think it's cleaner if the files are copied to a stryker4s-tmp folder, like stryker does. Instead of in the user's tmp directory. Maybe we could put it in target/stryker4s-tmp, as the target folder should already be in the user's gitignore.
- What would happen if a certain file is needed to compile/run tests, but is in the gitignore. Not sure how often this happens though

@nicojs Any other things you came across while implementing this that we might have to pay attention to?

**Comment by legopiraat** [comment]
@hugo-vrijswijk 

> What would happen if a certain file is needed to compile/run tests, but is in the gitignore. Not sure how often this happens though

This would be a very big edge case, the only thing i can think of is binary files that are needed for the test run, which might not be that smart in the first place.
