### ISSUE TITLE
Configuration key 'test-runner' is not picked up by command-runner

### ISSUE THREAD

**Issue by mdbergmann** [stryker-mutator/stryker4s#718]
Relates to: #36

### Summary

Trying to run stryker4s using command-runner fails because it does not pick up the `test-runner` configuration key and hence doesn't run the Gradle tests.

Running with coursier: 

```
coursier launch io.stryker-mutator::stryker4s-command-runner:0.11.0
```

```
11:20:33.524 WARN Stryker4s: The following configuration key(s) are not used, they could stem from an older stryker4s version: 'test-runner, log-level'.
```

### Stryker4s config

```hocon
stryker4s {
  reporters = ["console", "html"]
  scala-dialect = "2.12"
  test-runner {
      command = "./gradlew"
      args = "test"
  }
  log-level = DEBUG
  mutate = [ "src/main/**/*.scala" ]
}
```

### Stryker4s environment

```
stryker4s 0.11.0
```

Also happens with stryker4s 0.10.1.

### Your Environment
| software             | version(s) |
| -------------------- | ---------- |
| Scala version        |   2.12         |
| Build tool & version |   Gradle 6.8.1         | 
| Operating System     |    macOS        |

**Comment by mdbergmann** [comment]
I can have a look but some guidance would be helpful.
I'd imagine it should be somewhere in core where the config is read, or?

**Comment by hugo-vrijswijk** [comment]
Yes! The issue comes from reading config twice into two different case classes. Stryker4s reads the user [`Config`](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/config/Config.scala) once in [core](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/run/Stryker4sRunner.scala#L22) and the [`ProcessRunnerConfig`](https://github.com/stryker-mutator/stryker4s/blob/master/command-runner/src/main/scala/stryker4s/command/config/ProcessRunnerConfig.scala) in [command-runner](https://github.com/stryker-mutator/stryker4s/blob/master/command-runner/src/main/scala/stryker4s/command/Stryker4sMain.scala#L16).

The first config reading in core has [validation](https://github.com/stryker-mutator/stryker4s/blob/master/core/src/main/scala/stryker4s/config/ConfigReader.scala#L22) that checks if the config doesn't contain unused keys that could be misconfiguration. Because the command-runner config is in a separate case class it's recognized as an unused key for the core `Config`.

The proper fix for this I think is to only read the config once into a single case class in `ConfigReader#readConfig`. The ProcessRunnerConfig could extend the core Config, so all validation includes the command-runner config keys.

Out of scope for any fix, but this would be useful for the other modules, too! There's configuration in the core config case class that only applies to the [sbt plugin config](https://stryker-mutator.io/docs/stryker4s/configuration#sbt-plugin-config) and I can imagine the Maven plugin could get that in the future as well.

**Comment by cbrunnkvist** [comment]
On a related note: How _do_ we change the SBT task (equiv. "goal") that gets used by the sbt plugin? Is it supposed to be possible, but missed in its implementation?

**Comment by aishfenton** [comment]
Any update on this fix? Or any work around?

**Comment by hugo-vrijswijk** [comment]
@aishfenton Could you expand on what you are running into? For the the command-runner, you can ignore the log warning as it _is_ still picked up

**Comment by hugo-vrijswijk** [comment]
Warnings for keys that aren't used, but actually are are not an issue anymore in the next stryker4s release
